name: HPC
platform: VisiumHD

processed_data_dir: ${paths.processed_data_dir}/${.platform}/${.name}
interim_data_dir: ${paths.interim_data_dir}/${.platform}/${.name}

files:
  expression: expr.h5ad
  image: HE.tif
  mpp: MPP.txt
  general_svg: SVG_top_2000.txt
  top_svg: SVG_top_200.txt

metadata:
  spot_diameter_um: 55
  spot_center_distance_um: 100